old_sound_rabbit_mq:
    connections:
        default:
            host:     '%env(rabbit_mq_host)%'
            port:     '%env(rabbit_mq_port)%'
            user:     '%env(rabbit_mq_user)%'
            password: '%env(rabbit_mq_password)%'
            vhost:    '/'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3
            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false
            # requires php-amqplib v2.4.1+
            heartbeat: 0
    producers:
        send_event:
            connection:       default
            exchange_options: {name: 'send_event', type: direct}